name       : python-numba
version    : 0.56.4
release    : 12
source     :
    - https://github.com/numba/numba/archive/refs/tags/0.56.4.tar.gz : ab96b731fb9dee12b404b42b7c1fb82c119352648906a80526afa73658895b73
homepage   : http://numba.pydata.org
license    : BSD-2-Clause
component  : programming.python
summary    : NumPy aware dynamic Python compiler using LLVM
description: |
    Numba is an open source, NumPy-aware optimizing compiler for Python sponsored by Anaconda, Inc. It uses the LLVM compiler project to generate machine code from Python syntax.
builddeps  :
    - pkgconfig(python3)
    - numpy
rundeps    :
    - numpy
    - python-llvmlite
build      : |
    %python3_setup
install    : |
    %python3_install
