name       : python-numba
version    : 0.54.1
release    : 7
source     :
    - https://github.com/numba/numba/archive/refs/tags/0.54.1.tar.gz : 919b9269c253ccbc4110de736cc9e5c8abae68f452dd229734e3a25ac987a0e7
license    : BSD-2-Clause
homepage   : http://numba.pydata.org
component  : programming.python
summary    : NumPy aware dynamic Python compiler using LLVM
description: |
    Numba is an open source, NumPy-aware optimizing compiler for Python sponsored by Anaconda, Inc. It uses the LLVM compiler project to generate machine code from Python syntax.
builddeps  :
    - pkgconfig(python3)
    - numpy
rundeps    :
    - python-llvmlite
build      : |
    %python3_setup
install    : |
    %python3_install
