name       : python-numba
version    : 0.45.1
release    : 2
source     :
    - https://github.com/numba/numba/archive/0.45.1.tar.gz : 6a5da423d2f7aae9d84bb98166483d86e90146ab5cf15437506a5766cfae999e
license    : BSD-2-Clause
component  : programming.python
summary    : NumPy aware dynamic Python compiler using LLVM
description: |
    Numba is an open source, NumPy-aware optimizing compiler for Python sponsored by Anaconda, Inc. It uses the LLVM compiler project to generate machine code from Python syntax.
builddeps  :
    - python3-devel
    - numpy
rundeps    :
    - python-llvmlite
setup      : |
    %python3_setup
install    : |
    %python3_install
