name       : python-numba
version    : 0.55.1
release    : 9
source     :
    - https://github.com/numba/numba/archive/refs/tags/0.55.1.tar.gz : 542a9b514031f6afae971b627930fcaec057cdb604d54db7cbddfb050c580fb9
license    : BSD-2-Clause
homepage   : http://numba.pydata.org
component  : programming.python
summary    : NumPy aware dynamic Python compiler using LLVM
description: |
    Numba is an open source, NumPy-aware optimizing compiler for Python sponsored by Anaconda, Inc. It uses the LLVM compiler project to generate machine code from Python syntax.
builddeps  :
    - pkgconfig(python3)
    - numpy
rundeps    :
    - python-llvmlite
build      : |
    %python3_setup
install    : |
    %python3_install
