name       : python-numba
version    : 0.51.2
release    : 5
source     :
    - https://github.com/numba/numba/archive/0.51.2.tar.gz : c3385ddea40bcf2edfe405844ef9df97e23e5b8b7f635883a5e987f519e6441b
license    : BSD-2-Clause
homepage   : http://numba.pydata.org
component  : programming.python
summary    : NumPy aware dynamic Python compiler using LLVM
description: |
    Numba is an open source, NumPy-aware optimizing compiler for Python sponsored by Anaconda, Inc. It uses the LLVM compiler project to generate machine code from Python syntax.
builddeps  :
    - pkgconfig(python3)
    - numpy
rundeps    :
    - python-llvmlite
build      : |
    %python3_setup
install    : |
    %python3_install
