name       : python-numba
version    : 0.48.0
release    : 3
source     :
    - https://github.com/numba/numba/archive/0.48.0.tar.gz : 7cadc9075a2675c9152ee36642cea34210a41ca6c5cc6f1cb47d2834f0e67bdf
license    : BSD-2-Clause
homepage   : http://numba.pydata.org
component  : programming.python
summary    : NumPy aware dynamic Python compiler using LLVM
description: |
    Numba is an open source, NumPy-aware optimizing compiler for Python sponsored by Anaconda, Inc. It uses the LLVM compiler project to generate machine code from Python syntax.
builddeps  :
    - python3-devel
    - numpy
rundeps    :
    - python-llvmlite
setup      : |
    %python3_setup
install    : |
    %python3_install
